# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4dabc9c6ca8ce4889afbf55c5b8e6719"
name = "product-notes"
application_url = "https://ozone-result-helena-ty.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hospitality-test1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ozone-result-helena-ty.trycloudflare.com/auth/callback",
  "https://ozone-result-helena-ty.trycloudflare.com/auth/shopify/callback",
  "https://ozone-result-helena-ty.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
